modLoader="javafml" 
loaderVersion="[40,)"
license="MIT"
#issueTrackerURL="https://change.me.to.your.issue.tracker.example.invalid/" #optional
[[mods]]
modId="changedttu"
version="1.0"
displayName="Swylk Swa"
#updateJSONURL="https://change.me.example.invalid/updates.json"
#displayURL="https://change.me.to.your.mods.homepage.example.invalid/"
logoFile="cttu_likle.png"
credits="LtxProgrammer (Original Author of the Changed MC Mod)"
authors="PersonJ"
description='''
The near-raw madness of Anglish, and the near-unfetteredness of my own wants.
'''
[[dependencies.changedttu]]
    modId="changed"
    mandatory=true
    versionRange="[0.13.1, 0.14]"
    ordering="NONE"
    side="BOTH"

[[dependencies.changedttu]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18.2,1.19)"
    ordering="NONE"
    side="BOTH"